name: Merge DTDL

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    paths:
      - "Ontology/Willow/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token:  ${{ secrets.GITHUB_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build DTDL Merger
      run: dotnet build ./Tools/DTDLMerger/
    - name: Run DTDL Merger on Willow Ontology DTDLv3
      run: dotnet run --project ./Tools/DTDLMerger/ ./Ontology/Willow/ > ./Metadata/Willow.Ontology.DTDLv3.jsonld
    - name: Set .nuspec version
      id: set-version
      uses: vers-one/dotnet-project-version-updater@v1.2
      with:
        files: "Metadata/*.nuspec"
        version: ${{ github.event.inputs.version }}
    - name: 'Commit new .nuspec version'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Set .nuspec version to ${{ steps.set-version.outputs.newVersion }}
        branch: auto/${{ steps.set-version.outputs.newVersion }}
        create_branch: true
    - name: 'Create PR'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto/${{ steps.set-version.outputs.newVersion }}
        draft: false